# Generated by Django 2.2.7 on 2019-11-10 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_video_pitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_video_pitch', models.FileField(blank='True', upload_to='startup_uploads_pitch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload_pitch_deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_pitch_deck', models.FileField(blank='True', upload_to='startup_uploads_deck')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Upload_financials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_financials', models.FileField(blank='True', upload_to='startup_uploads_financials')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_first_name', models.CharField(max_length=150)),
                ('founder_last_name', models.CharField(max_length=150)),
                ('founder_prior', models.TextField()),
                ('founder_linkedin', models.URLField()),
                ('founder_instagram', models.URLField()),
                ('founder_contact_number', models.CharField(max_length=10)),
                ('founder_equity', models.IntegerField()),
                ('founder_education', models.TextField()),
                ('founder_achievements', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_entity_name', models.CharField(max_length=150)),
                ('startup_logo', models.ImageField(upload_to='startup_uploads_logo')),
                ('startup_contact_number', models.CharField(max_length=10)),
                ('startup_bio', models.TextField()),
                ('startup_disruption', models.TextField()),
                ('startup_website', models.URLField()),
                ('startup_brand_name', models.TextField()),
                ('startup_industry', models.TextField()),
                ('startup_advisors', models.TextField()),
                ('startup_linkedin', models.URLField()),
                ('user', models.OneToOneField(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cofounder4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cofounder3_first_name', models.CharField(max_length=150)),
                ('cofounder3_last_name', models.CharField(max_length=10)),
                ('cofounder3_prior', models.TextField()),
                ('cofounder3_linkedin', models.URLField()),
                ('cofounder3_instagram', models.URLField()),
                ('cofounder3_contact_number', models.IntegerField()),
                ('cofounder3_equity', models.IntegerField()),
                ('cofounder3_education', models.TextField()),
                ('cofounder3_achievements', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cofounder3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cofounder3_first_name', models.CharField(max_length=150)),
                ('cofounder3_last_name', models.CharField(max_length=10)),
                ('cofounder3_prior', models.TextField()),
                ('cofounder3_linkedin', models.URLField()),
                ('cofounder3_instagram', models.URLField()),
                ('cofounder3_contact_number', models.IntegerField()),
                ('cofounder3_equity', models.IntegerField()),
                ('cofounder3_education', models.TextField()),
                ('cofounder3_achievements', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cofounder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cofounder_first_name', models.CharField(max_length=150)),
                ('cofounder_last_name', models.CharField(max_length=10)),
                ('cofounder_prior', models.TextField()),
                ('cofounder_linkedin', models.URLField()),
                ('cofounder_instagram', models.URLField()),
                ('cofounder_contact_number', models.IntegerField()),
                ('cofounder_equity', models.IntegerField()),
                ('cofounder_education', models.TextField()),
                ('cofounder_achievements', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
