# Generated by Django 2.2.7 on 2019-11-19 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startup', '0003_auto_20191110_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup_Funding_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_location', models.TextField()),
                ('startup_funding_need', models.TextField()),
                ('startup_business_model', models.TextField()),
                ('startup_fund_utilize_time', models.TextField()),
                ('startup_stage', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
