# Generated by Django 2.2.7 on 2019-11-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0004_startup_funding_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='startup_business_model',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='startup_fund_utilize_time',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='startup_funding_need',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='startup_location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='startup_stage',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
