# Generated by Django 2.2 on 2020-02-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
