# Generated by Django 2.2 on 2020-02-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
