# Generated by Django 2.2.7 on 2019-11-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorthesis',
            name='geography',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
