# Generated by Django 2.2.7 on 2019-11-15 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investor', '0002_investorthesis_geography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investorthesis',
            old_name='exit_time',
            new_name='invesor_ticket_size',
        ),
        migrations.RenameField(
            model_name='investorthesis',
            old_name='geography',
            new_name='investor_exit_time',
        ),
        migrations.RenameField(
            model_name='investorthesis',
            old_name='return_expectp',
            new_name='investor_geography',
        ),
        migrations.RenameField(
            model_name='investorthesis',
            old_name='return_expectx',
            new_name='investor_return_expectp',
        ),
        migrations.RenameField(
            model_name='investorthesis',
            old_name='stage',
            new_name='investor_return_expectx',
        ),
        migrations.RenameField(
            model_name='investorthesis',
            old_name='ticket_size',
            new_name='investor_stage',
        ),
        migrations.AddField(
            model_name='investorthesis',
            name='user',
            field=models.OneToOneField(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default='True',
        ),
    ]
