# Generated by Django 2.2.7 on 2019-11-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0003_auto_20191115_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorthesis',
            name='invesor_ticket_size',
            field=models.TextField(max_length=150),
        ),
    ]
