# Generated by Django 2.2.7 on 2019-11-20 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0007_auto_20191120_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investordetail',
            name='user',
            field=models.OneToOneField(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investorthesis',
            name='user',
            field=models.OneToOneField(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
