# Generated by Django 2.2 on 2020-02-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0008_auto_20191120_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorthesis',
            name='investor_return_expectp',
        ),
        migrations.AlterField(
            model_name='investordetail',
            name='investor_logo',
            field=models.ImageField(default='/img/HRS.PNG', upload_to='investor_uploads_logo'),
        ),
    ]
